name: Test

on:
  push:
    branches:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .
    - name: Run tests
      run: find $GITHUB_WORKSPACE
