name: Test

on:
  push:
    branches:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE
        apt update -y
        apt install -y \
            make git binutils autoconf automake autotools-dev csh g++ libtool
        make get_dependencies
        make build
        ASSERT_PROGRAM=dist/assert make tests
